<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_logos_1</name>
   <tag></tag>
   <elementGuidId>42d9a1a9-7780-4b19-9cee-e56ec347339c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logos</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageBody&quot;)/div[@class=&quot;container container_main&quot;]/div[@class=&quot;content&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;col right&quot;]/span[@class=&quot;logos&quot;]</value>
   </webElementProperties>
</WebElementEntity>
