<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berlin</name>
   <tag></tag>
   <elementGuidId>adbe5d05-2aa4-4f6a-8e7c-d54a54bfae94</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styledSelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berlin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentWrapper&quot;)/div[@class=&quot;block block_results_tiles block_gray&quot;]/div[@class=&quot;wizard_2_form lobCongressroom func-lob-congressroom&quot;]/div[@class=&quot;open_form v3 opn&quot;]/div[@class=&quot;main_form_all&quot;]/div[@class=&quot;hotel_page_wizard&quot;]/form[1]/div[@class=&quot;border_wrap&quot;]/div[@class=&quot;wizard_step1 wizard wizard-step-one&quot;]/div[@class=&quot;formArea&quot;]/div[@class=&quot;wizard_step_part search timeAndPlaceSection time-place-section&quot;]/div[@class=&quot;place inline-element&quot;]/div[@class=&quot;select undefined&quot;]/div[@class=&quot;styledSelect&quot;]</value>
   </webElementProperties>
</WebElementEntity>
