<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rume</name>
   <tag></tag>
   <elementGuidId>be4f4562-3634-41f2-a7f5-ccd693a0f05a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>step_name title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Räume</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Räume</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentWrapper&quot;)/div[@class=&quot;block block_results_tiles block_gray&quot;]/div[@class=&quot;wizard_2_form lobCongressroom func-lob-congressroom&quot;]/div[@class=&quot;open_form v3 opn&quot;]/div[@class=&quot;main_form_all&quot;]/div[@class=&quot;hotel_page_wizard&quot;]/form[1]/div[@class=&quot;border_wrap&quot;]/div[@class=&quot;wizard_step1 wizard wizard-step-one&quot;]/div[@class=&quot;formArea&quot;]/div[@class=&quot;lobSectionCongressroom room-section&quot;]/div[@class=&quot;daysContainer section-rooms-container rooms-container&quot;]/div[2]/div[@class=&quot;dayContainer&quot;]/div[@class=&quot;rooms inline-element&quot;]/div[@class=&quot;r_num label&quot;]/span[@class=&quot;step_name title&quot;]</value>
   </webElementProperties>
</WebElementEntity>
