<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ansicht</name>
   <tag></tag>
   <elementGuidId>a8818f42-b3f2-428c-ae4e-5310d6704497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;applicationcache audio canvas canvastext emoji indexeddb indexeddb-deletedatabase json unicode video cssanimations supports csstransforms3d filereader localstorage no-websqldatabase websockets no-pointerevents fix-spin&quot;]/body[@class=&quot;unselectable&quot;]/div[@class=&quot;smart-dropdown-container dropdown open file&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[@class=&quot;io-ox-action-link&quot;][count(. | //a[@href = '#' and (text() = 'Ansicht' or . = 'Ansicht')]) = count(//a[@href = '#' and (text() = 'Ansicht' or . = 'Ansicht')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>io-ox-action-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>view_new</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section</name>
      <type>Main</type>
      <value>default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prio</name>
      <type>Main</type>
      <value>lo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>io.ox/mail/actions/view-attachment</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondragstart</name>
      <type>Main</type>
      <value>return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ansicht</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;applicationcache audio canvas canvastext emoji indexeddb indexeddb-deletedatabase json unicode video cssanimations supports csstransforms3d filereader localstorage no-websqldatabase websockets no-pointerevents fix-spin&quot;]/body[@class=&quot;unselectable&quot;]/div[@class=&quot;smart-dropdown-container dropdown open file&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[@class=&quot;io-ox-action-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
